name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "node scripts/with-database-url.mjs npx prisma generate"
dev = "node scripts/with-database-url.mjs npx prisma migrate deploy && node scripts/with-database-url.mjs npm exec react-router dev"
