import { sectionBuildLibrary } from "./section-library";
import { CAMPAIGN_SECTION_TYPES } from "./types";

export const NEWSLETTER_SKELETON_PROMPT = `## The one-prompt newsletter skeleton
This is a single promotional campaign email, not a lifecycle sequence step — it gets one shot to earn attention, so build it like a real marketing moment a merchant would be proud to send, not a plain notice with a product row underneath. Aim for the ambition of a well-funded DTC brand's campaign send: a genuine hero moment, confident scale contrast, and a composition that could only belong to this specific brief.

Structure every newsletter as:
1. An outer <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"> with a solid background-color, containing one centered <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" align="center"> capped at max-width: 600px via inline style.
2. A confident hero moment: the shop name in the serif display treatment, then a large, editorial headline that carries real personality — big type scale, generous letter-spacing, and/or a deliberate color block or divider behind it. This is the moment that has to stop a scroll; give it real visual weight, not a small centered line of text sitting alone in whitespace.
3. One short supporting paragraph that fulfills the merchant's campaign brief. Keep claims proportional to exactly what the brief says.
4. When relevant products were supplied, stage them as a genuine visual moment, not a plain uniform row: use deliberate scale contrast (one dominant hero product plus smaller supporting ones) or an even grid — whichever the brief and product count actually suit — with real image, title, and price. Do not invent a product, price, variant, or availability claim.
4a. Each supplied product may include a cutoutImageUrl: the exact same real photo with its background professionally removed, hosted at its own real URL. Use judgment about which version serves the composition: reach for the cutout when the moment wants an isolated, "floating" product-hero look against a color field or bold typographic background; keep the natural imageUrl photo when a photographic, in-context feel serves the brief better (a lifestyle scene, a busy grid of several items together). Never show both versions of the same product in the same email, and never alter either URL — use exactly what was supplied.
4b. The user message may also list photographs generated specifically for this campaign, each with a key, a role (hero, editorial, look, scene), its pixel size, alt text, and the real products it shows. Use every listed photo exactly once, in the section the art director's plan assigns it to, at full container width or as a deliberate large block — they are visual centerpieces, not thumbnails. Never lay text over a photo; keep every word as live HTML beside, above, or below it. Apply the same <img> sizing rules as every other image (width attribute, height:auto, never a fixed height or crop) and use the supplied alt text. A generated photo that shows a real product does not replace that product's real photo wherever the product itself is presented (a feature card, grid, or step) — those still use imageUrl or cutoutImageUrl. A photo's URL may be a pending placeholder on the host pending-photo.nomi.invalid, because the photo is still rendering while you write: use it exactly as given as that <img>'s src; it is swapped for the real hosted URL afterwards, and if the photo doesn't survive review the <img> alone is removed, so place each photo in its own cell and never make surrounding copy depend on it.
5. Calls-to-action are bulletproof table-based buttons with real presence — generous padding, a confident label, a colour that earns its place in the palette. Every button must link to a real supplied destination: a product URL for that product, a supplied collection URL, or the supplied storefront URL for a general "shop" action. Use at most one primary filled button per section and keep secondary actions outlined. If no suitable URL was supplied for a button, omit that button entirely; never use href="#". Every newsletter must still contain at least one prominent primary button to a real destination — the storefront homepage is always supplied for exactly this — placed where the plan puts the call to action (or, without a plan, where it reads most naturally).
6. When a real discount code was supplied, present it as a small designed moment rather than a bare bordered box — something with the character of a ticket stub, a voucher, or a wax-sealed note, built entirely from table cells, borders, dashed or dotted rules, and typography (no images, no SVG, no CSS backgrounds or gradients).
7. A minimal footer with the shop name and a restrained marketing-email note. Do not invent a postal address or unsubscribe URL; delivery infrastructure adds compliance links later.
8. Make the whole email feel designed specifically for this brief, never a generic template reused for every campaign. Two decoration tools are both fully available, and can be combined: a sparing, well-placed emoji or plain-text glyph (✦, ❆, 🎄, 🔔, and the like) as a light accent — next to a kicker, framing a headline, marking a footer note — and, for a more deliberate, larger motif that deserves real presence (a hero-scale seasonal symbol, a badge, a ticket stub), a genuine constructed graphic built from table cells, color, borders, rules, dividers, and spacing per 8a. Reach for whichever fits the moment: a glyph for a light seasonal touch, a real construction when the brief wants a proper visual centerpiece. Don't default to only one of the two for every campaign — vary it brief to brief the same way you vary everything else.
8a. The reliable technique for a recognizable silhouette (a Christmas tree, a star, a wreath, a gift box, a mountain, an arrow) is stacking: a long sequence of centered <td> cells in one column, each a solid background-color, each row wider than the row above it, with no gap between rows — many thin steps read as a smooth cone/triangle; a handful of thick steps reads as a stack of blocks, which fails. Use at least 10–14 rows for a tapering silhouette, each only 8–14px tall, with the width increasing by a small, fairly even amount row over row (for example: a 30px-wide top row growing to a 260–300px-wide bottom row across those rows) so the outline is a smooth triangle, not a wedding cake or gift-box stack.
For a Christmas tree specifically: the foliage MUST be a genuine, recognizable evergreen green — this overrides the campaign's invented brand palette for the foliage itself, because a tree rendered in the brand's own tan, gold, pink, or neutral tones will read as an abstract stack, not a tree; reserve the brand's own accent color for the ornaments, star, and any ribbon so the moment still feels on-brand. A single, well-chosen flat green applied evenly across every row is a clean, finished look on its own — that restraint is the point, don't add busywork on top of it. Only if it clearly earns its place, you may step through 2–3 close shades of that same green from a slightly lighter top row to a slightly deeper base row for subtle depth; keep any such shift subtle, since a loud, high-contrast banding effect reads as cluttered rather than premium. Do not run one continuous stripe or line down the tree — that reads as a ribbon on a box. Instead scatter a small, restrained number of ornaments — cells around 10–14px with border-radius:50% so they read as round baubles (a client that ignores border-radius still shows a small colored square, an acceptable finished look) — in 1–2 accent colors, placed with a little organic rhythm across the lower two-thirds of the tree: not a perfect grid, not clustered, and never on the top couple of rows where a tree naturally has little room. A handful of ornaments reads as finished; too many reads as busy. Top the tree with a small diamond shape — one small cell with transform: rotate(45deg) in a warm gold or the brand's accent color (a client that ignores the rotation still shows a small gold square, which still finishes the tree cleanly). Finish with a trunk: a short, narrower, warm brown cell centered beneath the base row. Be honest with yourself about the result: this is a stylised, minimalist, geometric tree icon — like a holiday card or wordmark motif — not a photorealistic illustration; a clean, restrained, well-proportioned version of this reads better than an overworked, busy one every time. The same width-stepping-plus-color-blocking idea builds other real shapes: a star from overlapping stepped rows at two angles-worth of width sequences, a wreath from a ring of small evenly-spaced colored cells around empty center space, a gift box from a rectangle cell plus a thin crossing band of a second color as the ribbon. Treat this as genuine visual craft worth real effort, not a decorative afterthought — it is what makes an email feel art-directed instead of templated.
8b. Beyond specific shapes, also reach for other invented decorative objects and motifs the same way: badge and ribbon shapes for a flash sale, warm open color fields for a summer brief, a ticket-stub or wax-seal treatment for a discount code (per rule 6). Vary the palette, ornamentation, and layout rhythm from brief to brief, and let real scale contrast — one very large element against much smaller ones — do the work instead of everything being the same size.
9. Editable seams: mark the handful of elements a merchant can safely hand-edit later, without changing anything else in the design. Wrap the exact headline text (from rule 2) in an element with data-nomi-seam="headline". Wrap the exact supporting-paragraph text (rule 3) in an element with data-nomi-seam="body". If you added a short kicker/eyebrow line above the headline, wrap its exact text in an element with data-nomi-seam="eyebrow"; omit this seam entirely when there is no such line. Wrap only the CTA link's visible label text (not the whole button) in an element with data-nomi-seam="cta-label"; omit this seam entirely when there is no CTA. Wrap the exact footer copy text in a single element with data-nomi-seam="footer". On every real product photo <img> (whichever of imageUrl/cutoutImageUrl you used), add data-nomi-seam="product" and data-nomi-product-id="<the exact id supplied for that product>"; add that same data-nomi-seam="product" data-nomi-product-id="<id>" to its enclosing <a> when the photo links to that product, so the photo and its link stay paired. On every generated photograph from rule 4b, add data-nomi-seam="image" so the merchant can swap it later. Every other piece of customer-facing copy is editable too: wrap each section heading, pull statement, closing-band line and sentence, product-card line, callout name and line, benefit title and line, step title and line, and photo caption in its own element with data-nomi-seam="text". Every button other than the primary CTA gets data-nomi-seam="button" on an element wrapping only its visible label text, inside its <a>. Style the copy however the design calls for; a seam simply wraps that line or phrase as designed. Never put a text or button seam on the headline, eyebrow, body, CTA label, or footer, which keep their own seams above, and never on a price, a discount code, or a product name, which must stay exactly as supplied. Every seam-tagged <img> must also carry explicit width and height attributes matching its rendered size, and a real, specific alt attribute. Never seam-tag any invented decorative object, motif, glyph, or constructed graphic (per rules 8–8b) — those are part of the composition itself, not merchant-editable content, and must stay exactly as designed. These attributes are inert metadata: never style them, never let them affect layout, and never omit them from a seam-eligible element.

The merchant's brief is authoritative. A percentage or price in it can be repeated, but never turn that into a discount code unless an actual code appears verbatim in the brief. Never invent end dates, scarcity, eligibility rules, testimonials, shipping promises, or legal terms. Decoration is built from color, shape, typography, and sparing glyphs only, per rules 8–8b — never invent, describe, or imply a product photo or lifestyle image beyond the real product images (and their optional real cutout versions) and the generated photographs listed in the user message. Never reference any image URL that was not supplied.

Write the HTML compactly: no indentation, no blank lines, no HTML comments, and no repeated style declarations a parent cell already sets. Spend the output on the design, not on whitespace — the document has a fixed length budget, and a long email that runs out of room is thrown away.

## Section library
When the user message includes an art director's section plan, build exactly those sections, in that order, each fulfilling its stated purpose with the products and photo it names — the plan is the composition, not a suggestion. Without a plan, compose freely from the rules above and draw on this library where it helps. Everything below is built from nested tables, inline styles, borders, background colours, and typography only.
${sectionBuildLibrary(CAMPAIGN_SECTION_TYPES)}`;
