// Campaigns is the durable index for Nomi's campaign workflow. Campaigns
// are one-prompt drafts backed by a real Campaign table (see
// prisma/schema.prisma) and generated by the same Claude engine as every
// other Nomi email (app/email-engine). The picker UI below searches the
// merchant's real Shopify catalogue — no dummy products, no placeholder
// photos.
import { useEffect, useRef, useState } from "react";
import type { ActionFunctionArgs, HeadersFunction, LoaderFunctionArgs } from "react-router";
import { Form, Link, useFetcher, useLoaderData, useSearchParams } from "react-router";
import { boundary } from "@shopify/shopify-app-react-router/server";
import { authenticate } from "../shopify.server";
import db from "../db.server";
import type { CampaignMetadataActionResult } from "./app.campaigns.metadata";
import { generateNewsletterEmail } from "../email-engine/generate-newsletter-email";
import { optimizeEmailImageUrl } from "../dashboard/email-image-url.server";
import { loadShopFooterAddress, resolveSenderFooter } from "../dashboard/sender-footer.server";
import { withComplianceFooter } from "../email-engine/compliance-footer";

// Merchant previews show the same footer customers get: the business
// address plus an Unsubscribe link (inert here; the real per-recipient link
// is added at send time).
async function previewFooterLine(admin: Parameters<typeof loadShopFooterAddress>[0], shop: string) {
  const [settings, shopAddress] = await Promise.all([
    db.shopSettings.findUnique({ where: { shop } }),
    loadShopFooterAddress(admin),
  ]);
  return resolveSenderFooter(settings, shopAddress).line;
}
import { EMAIL_GENERATION_PAUSED } from "../email-engine/generation-status";
import { EMAIL_LANGUAGES, EMAIL_TONES, type EmailLanguage, type EmailTone } from "../email-engine/types";
import {
  isBackgroundRemovalConfigured,
  removeImageBackground,
} from "../email-engine/background-removal";
import {
  imageDimensions,
  isImageGenerationConfigured,
} from "../email-engine/image-generation";
import {
  finalizeSections,
  planCampaignCreative,
  type CampaignImageBrief,
  type CampaignPlanInput,
} from "../email-engine/campaign-creative-plan";
import { renderReviewedPhoto } from "../dashboard/generated-photo.server";
import {
  generatedPhotoPlaceholder,
  resolveGeneratedPhotoPlaceholders,
} from "../email-engine/generated-photo-slots";
import type {
  NewsletterGeneratedImage,
  NewsletterProduct,
  NewsletterSection,
} from "../email-engine/types";
import { loadApprovedBrandIdentity } from "../email-delivery/approved-brand.server";
import { getApprovedBrandStudioFamily } from "../brand-studio/approved-family";
import { loadDashboardShopName } from "../dashboard/dashboard-data.server";
import { getSendingDomainSummary } from "../email-delivery/domains.server";
import { CAMPAIGN_LIMIT_MESSAGE, UNVERIFIED_CAMPAIGN_LIMIT, campaignLimitReached } from "../email-delivery/sending-domain";
import { checkAllowance, recordUsage } from "../billing/usage.server";
import {
  loadCampaignCollectionProducts,
  loadCampaignStoreLinks,
  loadCampaignProductsByIds,
  searchCampaignCollections,
  searchCampaignProducts,
  uploadImageBufferToShopify,
  type CampaignCatalogCollection,
  type CampaignCatalogProduct,
  type GraphqlAdmin,
} from "../dashboard/campaign-catalog.server";
import {
  CollectionPicker,
  GENERATE_ERROR_STYLE,
  MultiProductPicker,
  PROMPT_TOOL_STYLE,
  SingleProductPicker,
  useOutsideClose,
} from "../components/catalog-pickers";
import { GeneratingProgress } from "../components/generating-progress";

const CAMPAIGN_PAGE_SIZE = 12;

function resolveCampaignLanguage(value: string | undefined): EmailLanguage {
  return EMAIL_LANGUAGES.some(({ code }) => code === value) ? (value as EmailLanguage) : "en";
}
function resolveCampaignTone(value: string | undefined): EmailTone {
  return EMAIL_TONES.some(({ code }) => code === value) ? (value as EmailTone) : "warm-plain";
}
function formatCampaignDate(date: Date): string {
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}
function parseDateOrNull(value: string | null | undefined): Date | null {
  if (!value) return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const { session, admin } = await authenticate.admin(request);
  const url = new URL(request.url);

  // Catalog search for the picker UI — real store data, not the campaign list.
  const kind = url.searchParams.get("kind");
  if (kind === "products") {
    const products = await searchCampaignProducts(admin, url.searchParams.get("q") ?? "");
    return { products };
  }
  if (kind === "collections") {
    const collections = await searchCampaignCollections(admin, url.searchParams.get("q") ?? "");
    return { collections };
  }

  const search = url.searchParams.get("q")?.trim().slice(0, 100) ?? "";
  const requestedPage = Number(url.searchParams.get("page") ?? "1");
  const page = Number.isInteger(requestedPage) && requestedPage > 0 ? requestedPage : 1;

  const where = {
    shop: session.shop,
    ...(search ? { name: { contains: search } } : {}),
  };
  const total = await db.campaign.count({ where });
  // The unverified-domain cap counts every campaign, not the search result.
  const [shopCampaignCount, sendingDomain, postalLine] = await Promise.all([
    search ? db.campaign.count({ where: { shop: session.shop } }) : Promise.resolve(total),
    getSendingDomainSummary(session.shop),
    previewFooterLine(admin, session.shop),
  ]);
  const pageCount = Math.max(1, Math.ceil(total / CAMPAIGN_PAGE_SIZE));
  const safePage = Math.min(page, pageCount);
  const rows = await db.campaign.findMany({
    where,
    orderBy: { createdAt: "desc" },
    skip: (safePage - 1) * CAMPAIGN_PAGE_SIZE,
    take: CAMPAIGN_PAGE_SIZE,
  });

  return {
    search,
    page: safePage,
    total,
    pageCount,
    sendingDomain,
    campaignLimit: {
      max: UNVERIFIED_CAMPAIGN_LIMIT,
      used: shopCampaignCount,
      reached: campaignLimitReached(shopCampaignCount, sendingDomain?.status),
    },
    campaigns: rows.map((row) => ({
      id: row.id,
      name: row.name,
      date: formatCampaignDate(row.updatedAt),
      emails: 1,
      status: capitalize(row.status),
      subject: row.subject ?? "",
      previewText: row.previewText ?? "",
      html: row.html ? withComplianceFooter(row.html, { postalLine, unsubscribeUrl: null }) : "",
    })),
  };
};

type GenerateCampaignRequest = {
  prompt: string;
  feature: Feature;
  productIds: string[];
  collectionId: string | null;
  discountMethod: DiscountMethod;
  discountCode: string | null;
  discountType: DiscountType;
  discountValue: string | null;
  startAt: string | null;
  endAt: string | null;
};

type NormalizedDiscount = {
  method: DiscountMethod;
  code: string | null;
  type: DiscountType;
  value: string | null;
  currency: string;
  startsAt: Date | null;
  endsAt: Date | null;
};

function normalizeDiscount(parsed: GenerateCampaignRequest): NormalizedDiscount {
  if (parsed.discountMethod !== "code") {
    return { method: "none", code: null, type: "percentage", value: null, currency: "USD", startsAt: null, endsAt: null };
  }
  const code = (parsed.discountCode ?? "").trim().slice(0, 40) || null;
  const value = (parsed.discountValue ?? "").trim().slice(0, 20) || null;
  const type: DiscountType = parsed.discountType === "fixed" ? "fixed" : "percentage";
  return {
    method: code && value ? "code" : "none",
    code,
    type,
    value,
    currency: "USD",
    startsAt: parseDateOrNull(parsed.startAt),
    endsAt: parseDateOrNull(parsed.endAt),
  };
}

// The brief is authoritative per NEWSLETTER_SKELETON_PROMPT — supplying the
// real code and dates verbatim here is what lets the model use them without
// inventing anything.
function withDiscountContext(prompt: string, discount: NormalizedDiscount): string {
  if (discount.method !== "code" || !discount.code || !discount.value) return prompt;
  const amountLabel = discount.type === "percentage" ? `${discount.value}%` : `${discount.value} ${discount.currency}`;
  const windowLabel =
    discount.startsAt && discount.endsAt
      ? ` Valid ${discount.startsAt.toISOString().slice(0, 10)} through ${discount.endsAt.toISOString().slice(0, 10)}.`
      : "";
  return `${prompt}\n\nReal discount to mention: code "${discount.code}" for ${amountLabel} off.${windowLabel} Use this exact code; never invent a different one.`;
}

function discountLabel(discount: NormalizedDiscount): string {
  if (discount.method !== "code" || !discount.code || !discount.value) return "No discount";
  const suffix = discount.type === "percentage" ? "%" : ` ${discount.currency}`;
  return `Discount ${discount.value}${suffix} · Code ${discount.code}`;
}

// A background-removed "cutout" of one product's real photo, offered to the
// generator alongside the original so it can pick whichever suits the
// composition (see newsletter-prompt.ts). Best-effort and entirely optional:
// unset REMOVE_BG_API_KEY and this always returns null with no extra cost or
// latency. ProductImageCutout caches a hit so the same product is never
// billed to the (paid, third-party) removal API more than once.
async function resolveProductCutout(
  admin: GraphqlAdmin,
  shop: string,
  productId: string,
  imageUrl: string,
): Promise<string | null> {
  if (!isBackgroundRemovalConfigured()) return null;
  const cached = await db.productImageCutout.findUnique({
    where: {
      shop_productId_sourceImageUrl: { shop, productId, sourceImageUrl: imageUrl },
    },
  });
  if (cached) return cached.cutoutImageUrl;

  const removed = await removeImageBackground(imageUrl);
  if (!removed) return null;
  const uploadedUrl = await uploadImageBufferToShopify(admin, {
    bytes: removed.bytes,
    contentType: removed.contentType,
    filename: `${productId.replace(/[^a-zA-Z0-9]/g, "-")}-cutout.png`,
    alt: "Product photo with background removed",
  });
  if (!uploadedUrl) return null;

  try {
    await db.productImageCutout.create({
      data: { shop, productId, sourceImageUrl: imageUrl, cutoutImageUrl: uploadedUrl },
    });
  } catch {
    // A concurrent request may have already cached this exact triple — the
    // upload above still succeeded, so use it regardless of the race.
  }
  return uploadedUrl;
}

// One planned photo, generated, reviewed, and hosted by the shared helper
// (dashboard/generated-photo.server.ts). Resolves to the hosted URL or null.
async function renderCampaignPhoto(
  admin: GraphqlAdmin,
  input: CampaignPlanInput,
  image: CampaignImageBrief,
  filename: string,
): Promise<string | null> {
  const result = await renderReviewedPhoto(admin, {
    brief: image,
    shopName: input.shopName,
    products: input.products,
    filename,
  });
  return result.url;
}

// The campaign's creative direction (see campaign-creative-plan.ts). Claude
// plans the whole email — which sections, how many, in what order, and
// whether any earns a generated photo — then the photos start rendering in
// the background. The designer gets the plan straight away with a pending
// placeholder per photo (generated-photo-slots.ts), so writing the email
// and rendering its photos overlap instead of running back to back.
// Best-effort end to end: unset OPENAI_API_KEY skips photos, and a planning
// error means the designer composes freely exactly as before.
async function planCreativeDirection(
  admin: GraphqlAdmin,
  input: CampaignPlanInput,
): Promise<{
  concept: string | null;
  sections: NewsletterSection[];
  generatedImages: NewsletterGeneratedImage[];
  photos: Promise<Map<string, string | null>>;
}> {
  let plan: Awaited<ReturnType<typeof planCampaignCreative>>;
  try {
    plan = await planCampaignCreative(input);
  } catch (error) {
    console.error("Campaign creative planning failed:", error);
    return { concept: null, sections: [], generatedImages: [], photos: Promise.resolve(new Map()) };
  }
  console.info(
    `Campaign creative plan: ${plan.sections.map((section) => section.type).join(" → ")}; ` +
      `${plan.images.length} photo(s). ${plan.reasoning} ` +
      `(planner tokens in/out ${plan.usage.inputTokens}/${plan.usage.outputTokens})`,
  );

  const briefs = isImageGenerationConfigured() ? plan.images : [];
  // Data checks only (real products, collections, a discount code); photo
  // failures are handled after rendering by removing that one <img>.
  const sections = finalizeSections(plan.sections, {
    availableImages: new Map(briefs.map((image) => [image.key, image])),
    hasCollections: input.collections.length > 0,
    hasDiscountCode: input.hasDiscountCode,
  });
  const placed = new Set(sections.map((section) => section.imageKey).filter(Boolean));
  const toRender = briefs.filter((image) => placed.has(image.key));

  const stamp = Date.now();
  const photos = Promise.all(
    toRender.map(async (image, index) => {
      const url = await renderCampaignPhoto(
        admin,
        input,
        image,
        `nomi-campaign-${stamp}-${index + 1}-${image.role}.jpg`,
      );
      return [image.key, url] as const;
    }),
  ).then((entries) => new Map(entries));

  return {
    concept: plan.concept || null,
    sections,
    generatedImages: toRender.map((image) => ({
      key: image.key,
      url: generatedPhotoPlaceholder(image.key),
      alt: image.alt,
      role: image.role,
      ...imageDimensions(image.aspect),
      productIds: image.productIds,
    })),
    photos,
  };
}

export const action = async ({ request }: ActionFunctionArgs) => {
  const { session, admin } = await authenticate.admin(request);
  const formData = await request.formData();
  const payload = formData.get("payload");
  if (typeof payload !== "string") {
    return { error: "Missing request data." };
  }

  let parsed: GenerateCampaignRequest;
  try {
    parsed = JSON.parse(payload) as GenerateCampaignRequest;
  } catch {
    return { error: "Malformed request." };
  }

  if (EMAIL_GENERATION_PAUSED) {
    return { error: "Email generation is paused until you choose to start it." };
  }

  // Checked before any generation cost is spent.
  const [campaignCount, domain] = await Promise.all([
    db.campaign.count({ where: { shop: session.shop } }),
    getSendingDomainSummary(session.shop),
  ]);
  if (campaignLimitReached(campaignCount, domain?.status)) {
    return { error: CAMPAIGN_LIMIT_MESSAGE };
  }
  const allowance = await checkAllowance(session.shop, "campaign");
  if (!allowance.allowed) return { error: allowance.message ?? "Your plan's campaigns are used up." };

  const prompt = parsed.prompt.trim();
  if (!prompt || prompt.length > 1000) {
    return { error: "Describe the campaign in 1–1000 characters." };
  }

  const settings = await db.shopSettings.findUnique({
    where: { shop: session.shop },
    select: { language: true, tone: true },
  });
  const language = resolveCampaignLanguage(settings?.language);
  const tone = resolveCampaignTone(settings?.tone);

  let products: CampaignCatalogProduct[] = [];
  let featuredCollectionId: string | null = null;
  let featuredTitle: string | null = null;

  try {
    if (parsed.feature === "product") {
      products = await loadCampaignProductsByIds(admin, parsed.productIds.slice(0, 1));
      featuredTitle = products[0]?.title ?? null;
    } else if (parsed.feature === "all_products") {
      products = await loadCampaignProductsByIds(admin, parsed.productIds.slice(0, 3));
      featuredTitle = products.map((product) => product.title).join(", ") || null;
    } else if (parsed.feature === "collection" && parsed.collectionId) {
      const collection = await loadCampaignCollectionProducts(admin, parsed.collectionId);
      products = collection?.products ?? [];
      featuredCollectionId = parsed.collectionId;
      featuredTitle = collection?.title ?? null;
    }
  } catch (error) {
    console.error("Campaign catalog lookup failed:", error);
    return { error: "Couldn't load the selected products — try again." };
  }

  // An approved Brand Studio identity makes the campaign wear the merchant's
  // real brand (name, palette, voice, image treatment) instead of an
  // invented skin, and tells the photo planner what the store is about.
  // The brand name comes from Brand Studio's evidence (the merchant's real
  // name), never brandSystem.name, which names the creative direction.
  const [storeName, approvedBrand, brandProfile] = await Promise.all([
    loadDashboardShopName(admin),
    loadApprovedBrandIdentity(session.shop, null).catch(() => null),
    db.brandStudioProfile.findUnique({ where: { shop: session.shop } }).catch(() => null),
  ]);
  const brandIdentity = approvedBrand ?? undefined;
  const approvedFamily = brandIdentity && brandProfile ? getApprovedBrandStudioFamily(brandProfile) : null;
  const shopName = approvedFamily?.evidence.shopName?.trim() || storeName;
  const discount = normalizeDiscount(parsed);
  const enrichedPrompt = withDiscountContext(prompt, discount);

  // Best-effort: a failed or unconfigured cutout never blocks generation —
  // resolveProductCutout always falls back to null, and the prompt is told
  // to use the real photo whenever no cutout is present.
  // The cutout cache and remove.bg are keyed on the original photo URL, so
  // email-sized URLs are only swapped in after the cutout is resolved.
  const startedAt = Date.now();
  const storeLinksPromise = loadCampaignStoreLinks(admin);
  const productsWithCutouts = await Promise.all(
    products.map(async (product) => {
      const cutoutImageUrl = product.imageUrl
        ? await resolveProductCutout(admin, session.shop, product.id, product.imageUrl)
        : null;
      const [imageUrl, emailCutoutUrl] = await Promise.all([
        optimizeEmailImageUrl(product.imageUrl),
        optimizeEmailImageUrl(cutoutImageUrl, { transparent: true }),
      ]);
      return { ...product, imageUrl, cutoutImageUrl: emailCutoutUrl };
    }),
  );

  const newsletterProducts: NewsletterProduct[] = productsWithCutouts.map(
    ({ id, title, price, imageUrl, productUrl, cutoutImageUrl, productType, description }) => ({
      id,
      title,
      price,
      imageUrl,
      productUrl,
      cutoutImageUrl,
      productType: productType ?? null,
      description: description ?? null,
    }),
  );
  const storeLinks = await storeLinksPromise;
  // Every campaign carries a call to action, so a destination must always
  // exist: the shop's .myshopify.com address always serves its storefront
  // when the primary-domain lookup fails.
  const storefrontUrl = storeLinks.storefrontUrl ?? `https://${session.shop}`;
  const creative = await planCreativeDirection(admin, {
    shopName,
    prompt: enrichedPrompt,
    products: newsletterProducts,
    collections: storeLinks.collections,
    storefrontUrl,
    hasDiscountCode: discount.method === "code" && Boolean(discount.code),
    brandIdentity,
  });
  const plannedAt = Date.now();

  let html: string;
  try {
    html = await generateNewsletterEmail({
      shopName,
      language,
      tone,
      prompt: enrichedPrompt,
      products: newsletterProducts,
      generatedImages: creative.generatedImages,
      concept: creative.concept,
      sections: creative.sections,
      collections: storeLinks.collections,
      storefrontUrl,
      brandIdentity,
    });
  } catch (error) {
    console.error("Campaign generation failed:", error);
    return { error: error instanceof Error ? error.message : "Couldn't generate that campaign — try again." };
  }
  const writtenAt = Date.now();
  const photos = resolveGeneratedPhotoPlaceholders(html, await creative.photos);
  html = photos.html;
  console.info(
    `Campaign timing: planning ${Math.round((plannedAt - startedAt) / 1000)}s, ` +
      `email ${Math.round((writtenAt - plannedAt) / 1000)}s, ` +
      `waiting on photos ${Math.round((Date.now() - writtenAt) / 1000)}s; ` +
      `photos placed [${photos.placed.join(", ")}], removed [${photos.removed.join(", ")}]`,
  );

  const name = capitalize(prompt);
  const subject =
    discount.method === "code" && discount.value
      ? `${discount.value}${discount.type === "percentage" ? "%" : ` ${discount.currency}`} Off — ${name}`
      : name;
  const previewText = featuredTitle ? `Featuring ${featuredTitle}.` : "A new campaign from your shop.";

  const campaign = await db.campaign.create({
    data: {
      shop: session.shop,
      status: "draft",
      method: "ai",
      name,
      prompt,
      feature: parsed.feature,
      featuredProductIds: JSON.stringify(products.map((product) => product.id)),
      featuredCollectionId,
      discountMethod: discount.method,
      discountCode: discount.code,
      discountType: discount.type,
      discountValue: discount.value,
      discountStartsAt: discount.startsAt,
      discountEndsAt: discount.endsAt,
      subject,
      previewText,
      html,
    },
  });
  await recordUsage(session.shop, "campaign");

  return {
    campaign: {
      id: campaign.id,
      name: campaign.name,
      subject,
      previewText,
      discountLine: discountLabel(discount),
      html: withComplianceFooter(html, { postalLine: await previewFooterLine(admin, session.shop), unsubscribeUrl: null }),
    },
  };
};

// --- Create Campaign flow -------------------------------------------------
// A picker-driven creation experience: describe the campaign, search the real
// catalogue for what to feature, set a discount, then generate a real
// campaign draft with Claude.

type Feature = "product" | "collection" | "all_products";
type DiscountMethod = "code" | "none";
type DiscountType = "percentage" | "fixed";
type ModalStage = "closed" | "configure" | "generating";

// Mirrors the real pipeline (plan, then the email and its photos in
// parallel, then photo review and placement), paced by AI_LIVE_STEP_MS to
// the ~1–2 minutes a campaign actually takes.
const AI_ROWS = [
  "Reading your brief and products",
  "Planning the email's sections",
  "Designing the email and creating photos",
  "Checking every photo against your products",
  "Placing photos in your email",
  "Finalizing your email campaign",
];
const AI_LIVE_STEP_MS = 18_000;
const SETTLE_MS = 1500;

function randomDiscountCode() {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let out = "";
  for (let i = 0; i < 10; i += 1) out += chars[Math.floor(Math.random() * chars.length)];
  return out;
}
function capitalize(value: string) {
  return value.replace(/\b\w/g, (c) => c.toUpperCase());
}
function isoDateOffset(days: number) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
}


// The just-created campaign, shown as a card until the merchant views the list.
type Reveal = { id: string; title: string; subject: string; preview: string; discountLine: string; html: string };

function CreateCampaignModal({ stage, onClose, onGenerate, generatingStep,
  prompt, onPromptChange, feature, onFeatureProduct, onFeatureCollection,
  onFeatureAllProducts, selectedProduct, onSelectedProductChange, selectedCollection, onSelectedCollectionChange,
  selectedProducts, onSelectedProductsChange,
  discountMethod, onDiscountCode, onDiscountNone, discountCode,
  onDiscountCodeChange, onGenerateRandomCode, discountType, onDiscountTypeChange, discountValue,
  onDiscountValueChange, discountSuffix, startDate, onStartDateChange, startTime, onStartTimeChange,
  endDate, onEndDateChange, endTime, onEndTimeChange, generateError }: {
  stage: Extract<ModalStage, "configure" | "generating">;
  onClose: () => void;
  onGenerate: () => void;
  generatingStep: number;
  prompt: string;
  onPromptChange: (value: string) => void;
  feature: Feature;
  onFeatureProduct: () => void;
  onFeatureCollection: () => void;
  onFeatureAllProducts: () => void;
  selectedProduct: CampaignCatalogProduct | null;
  onSelectedProductChange: (product: CampaignCatalogProduct) => void;
  selectedCollection: CampaignCatalogCollection | null;
  onSelectedCollectionChange: (collection: CampaignCatalogCollection) => void;
  selectedProducts: CampaignCatalogProduct[];
  onSelectedProductsChange: (products: CampaignCatalogProduct[]) => void;
  discountMethod: DiscountMethod;
  onDiscountCode: () => void;
  onDiscountNone: () => void;
  discountCode: string;
  onDiscountCodeChange: (value: string) => void;
  onGenerateRandomCode: () => void;
  discountType: DiscountType;
  onDiscountTypeChange: (value: DiscountType) => void;
  discountValue: string;
  onDiscountValueChange: (value: string) => void;
  discountSuffix: string;
  startDate: string;
  onStartDateChange: (value: string) => void;
  startTime: string;
  onStartTimeChange: (value: string) => void;
  endDate: string;
  onEndDateChange: (value: string) => void;
  endTime: string;
  onEndTimeChange: (value: string) => void;
  generateError: string | null;
}) {
  useEffect(() => {
    if (stage !== "configure") return;
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [stage, onClose]);

  return (
    <div className="nomi-cc-backdrop" role="presentation">
      <div className="nomi-cc-modal" role="dialog" aria-modal="true" aria-label="Create Campaign">
        {stage === "configure" ? (
          <>
            <div className="nomi-cc-modal-head">
              <h2>Create Campaign</h2>
              <button type="button" className="nomi-cc-close" aria-label="Close" onClick={onClose}>
                <svg width="15" height="15" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5l14 14M19 5L5 19" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" /></svg>
              </button>
            </div>

            <div className="nomi-cc-body">
                <>
                  <div>
                    <span className="nomi-cc-label" style={{ color: "var(--nomi-cyan-700)", display: "inline-flex", alignItems: "center", gap: 5 }}>
                      Tell Nomi AI more about this campaign
                      <svg width="11" height="11" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l1.6 5.2L19 10l-5.4 1.8L12 17l-1.6-5.2L5 10l5.4-1.8Z" fill="#006786" /></svg>
                    </span>
                    <div className="nomi-cc-prompt-wrap">
                      <textarea className="nomi-cc-prompt" value={prompt} onChange={(e) => onPromptChange(e.target.value)} placeholder="e.g. flash sale, restock announcement, holiday gift guide" />
                      <div className="nomi-cc-prompt-tools">
                        <span title="Feature a product" className="nomi-cc-prompt-tool is-feature" style={PROMPT_TOOL_STYLE}>
                          <svg width="11" height="11" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7l8-4 8 4v10l-8 4-8-4Z" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinejoin="round" /></svg>
                        </span>
                      </div>
                    </div>
                    {generateError ? <p className="nomi-cc-generate-error" style={GENERATE_ERROR_STYLE}>{generateError}</p> : null}
                  </div>

                  <div>
                    <span className="nomi-cc-label">What should the campaign feature?</span>
                    <div className="nomi-cc-feature-row">
                      <button type="button" className={`nomi-cc-feature-btn${feature === "product" ? " is-active" : ""}`} onClick={onFeatureProduct}>Product</button>
                      <button type="button" className={`nomi-cc-feature-btn${feature === "collection" ? " is-active" : ""}`} onClick={onFeatureCollection}>Collection</button>
                      <button type="button" className={`nomi-cc-feature-btn${feature === "all_products" ? " is-active" : ""}`} onClick={onFeatureAllProducts}>All Products</button>
                    </div>
                    {feature === "collection" ? (
                      <>
                        <span className="nomi-cc-label" style={{ marginBottom: 6, fontWeight: 700, fontSize: 12 }}>Featured Collection</span>
                        <CollectionPicker value={selectedCollection} onChange={onSelectedCollectionChange} placeholder="Select a collection" />
                      </>
                    ) : feature === "product" ? (
                      <>
                        <span className="nomi-cc-label" style={{ marginBottom: 6, fontWeight: 700, fontSize: 12 }}>Featured Product</span>
                        <SingleProductPicker value={selectedProduct} onChange={onSelectedProductChange} placeholder="Select a product" />
                      </>
                    ) : (
                      <>
                        <span className="nomi-cc-label" style={{ marginBottom: 6, fontWeight: 700, fontSize: 12 }}>Showcase these products (up to 3)</span>
                        <MultiProductPicker value={selectedProducts} onChange={onSelectedProductsChange} max={3} />
                      </>
                    )}
                  </div>
                </>

              <div className="nomi-cc-discount-box">
                <span className="nomi-cc-discount-title">Campaign Discount</span>
                <span className="nomi-cc-label">Method</span>
                <div className="nomi-cc-feature-row">
                  <button type="button" className={`nomi-cc-feature-btn${discountMethod === "code" ? " is-active" : ""}`} onClick={onDiscountCode}>Discount Code</button>
                  <button type="button" className={`nomi-cc-feature-btn${discountMethod === "none" ? " is-active" : ""}`} onClick={onDiscountNone}>No Discount</button>
                </div>

                {discountMethod === "code" ? (
                  <>
                    <div className="nomi-cc-discount-row">
                      <span className="nomi-cc-fieldlabel">Discount Code</span>
                      <button type="button" className="nomi-cc-random-code" onClick={onGenerateRandomCode}>Generate random code</button>
                    </div>
                    <input key={discountCode} type="text" className="nomi-cc-input nomi-cc-code-input" value={discountCode} onChange={(e) => onDiscountCodeChange(e.target.value)} />

                    <span className="nomi-cc-label" style={{ fontWeight: 700, fontSize: 12 }}>Discount Value</span>
                    <div className="nomi-cc-value-row">
                      <select className="nomi-cc-select nomi-cc-value-select" value={discountType} onChange={(e) => onDiscountTypeChange(e.target.value as DiscountType)}>
                        <option value="percentage">Percentage</option>
                        <option value="fixed">Fixed amount</option>
                      </select>
                      <div className="nomi-cc-value-field">
                        <input type="number" className="nomi-cc-input nomi-cc-value-input" style={{ marginBottom: 0 }} value={discountValue} onChange={(e) => onDiscountValueChange(e.target.value)} />
                        <span className="nomi-cc-value-suffix">{discountSuffix}</span>
                      </div>
                    </div>

                    <span className="nomi-cc-label" style={{ fontWeight: 700, fontSize: 12 }}>Discount Active Dates</span>
                    <div className="nomi-cc-dates">
                      <div><small>Start date</small><input type="date" className="nomi-cc-date-input" value={startDate} onChange={(e) => onStartDateChange(e.target.value)} /></div>
                      <div><small>Start time</small><input type="time" className="nomi-cc-date-input" value={startTime} onChange={(e) => onStartTimeChange(e.target.value)} /></div>
                      <div><small>End date</small><input type="date" className="nomi-cc-date-input" value={endDate} onChange={(e) => onEndDateChange(e.target.value)} /></div>
                      <div><small>End time</small><input type="time" className="nomi-cc-date-input" value={endTime} onChange={(e) => onEndTimeChange(e.target.value)} /></div>
                    </div>
                  </>
                ) : null}
              </div>
            </div>

            <div className="nomi-cc-modal-foot">
              <button type="button" className="nomi-cc-discard" onClick={onClose}>Discard</button>
              <button type="button" className="nomi-cc-generate" onClick={onGenerate}>
                <svg width="12" height="12" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l1.6 5.2L19 10l-5.4 1.8L12 17l-1.6-5.2L5 10l5.4-1.8Z" fill="currentColor" /></svg>
                Generate
              </button>
            </div>
          </>
        ) : (
          <GeneratingProgress title="Generating Your Campaign" rows={AI_ROWS} step={generatingStep} note="This usually takes 1–2 minutes." />
        )}
      </div>
    </div>
  );
}

// Inlined rather than left to the nomi-campaign-preview-* classes in
// nomi.css: those classes were observed silently failing to apply live in
// this embedded-iframe context (plain black text, no radius/shadow, a bare
// blue underlined "Edit" link) even though the same stylesheet's rules
// render fine elsewhere — the identical failure mode CAMPAIGNS.md documents
// for the picker components above, and the same fix (inline style={}).
const PREVIEW_BACKDROP_STYLE: React.CSSProperties = {
  position: "fixed", inset: 0, zIndex: 520, display: "flex", alignItems: "center",
  justifyContent: "center", padding: 20, background: "rgba(32, 30, 29, .5)", boxSizing: "border-box",
};
const PREVIEW_MODAL_STYLE: React.CSSProperties = {
  width: "min(1040px, 94vw)", height: "min(94vh, 1040px)", maxHeight: "94vh",
  borderRadius: 14, background: "#ffffff", boxShadow: "0 40px 100px rgba(32, 30, 29, .35)",
  display: "flex", flexDirection: "column", overflow: "hidden", boxSizing: "border-box",
};
const PREVIEW_HEAD_STYLE: React.CSSProperties = {
  display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 20,
  padding: "20px 24px", borderBottom: "1px solid #eae7e7", flexShrink: 0,
};
const PREVIEW_HEADING_STYLE: React.CSSProperties = { minWidth: 0 };
const PREVIEW_H2_STYLE: React.CSSProperties = { margin: 0, font: '600 19px/1.3 Lora, Georgia, serif', color: "#201e1d" };
const PREVIEW_SUBJECT_STYLE: React.CSSProperties = { margin: "6px 0 0", fontSize: 13, color: "#605d5d", font: '13px/1.5 "IBM Plex Sans", sans-serif' };
const PREVIEW_ACTIONS_STYLE: React.CSSProperties = { display: "flex", alignItems: "center", gap: 8, flexShrink: 0, paddingTop: 2, position: "relative" };
const PREVIEW_EDIT_TRIGGER_STYLE: React.CSSProperties = {
  display: "inline-flex", alignItems: "center", gap: 6, height: 34, padding: "0 16px",
  borderRadius: 999, background: "#201e1d", color: "#f3f2f2", font: '600 13px/1 "IBM Plex Sans", sans-serif',
  border: 0, cursor: "pointer", whiteSpace: "nowrap",
};
const PREVIEW_EDIT_MENU_STYLE: React.CSSProperties = {
  position: "absolute", top: "calc(100% + 6px)", right: 0, zIndex: 30, minWidth: 232,
  display: "flex", flexDirection: "column", padding: 6, borderRadius: 10,
  background: "#ffffff", border: "1px solid #d7d3d3", boxShadow: "0 18px 44px rgba(32, 30, 29, .18)",
};
const PREVIEW_EDIT_MENU_ITEM_STYLE: React.CSSProperties = {
  display: "block", width: "100%", textAlign: "left", padding: "9px 10px", borderRadius: 6,
  border: 0, background: "transparent", color: "#201e1d", font: '13px/1.3 "IBM Plex Sans", sans-serif',
  cursor: "pointer", textDecoration: "none", boxSizing: "border-box",
};
const PREVIEW_CLOSE_STYLE: React.CSSProperties = {
  width: 30, height: 30, display: "grid", placeItems: "center", border: 0, borderRadius: 6,
  background: "transparent", color: "#605d5d", cursor: "pointer", flexShrink: 0,
};
const PREVIEW_CANVAS_STYLE: React.CSSProperties = {
  flex: 1, minHeight: 0, overflowY: "auto", background: "#f8f4f4", padding: 32,
  display: "flex", justifyContent: "center", boxSizing: "border-box",
};
const PREVIEW_FRAME_STYLE: React.CSSProperties = {
  width: 640, maxWidth: "100%", height: 2400, border: 0, borderRadius: 4,
  background: "#ffffff", boxShadow: "0 10px 30px rgba(32, 30, 29, .12)", flexShrink: 0,
};
const PREVIEW_EMPTY_STYLE: React.CSSProperties = {
  margin: 0, padding: "48px 24px", color: "#716d6d", fontSize: 13, textAlign: "center",
};

function CampaignPreviewModal({ campaign, onClose }: {
  campaign: { id: string; name: string; subject: string; previewText: string; html: string };
  onClose: () => void;
}) {
  const [subject, setSubject] = useState(campaign.subject);
  const [previewText, setPreviewText] = useState(campaign.previewText);
  const [menuOpen, setMenuOpen] = useState(false);
  const [editingMetadata, setEditingMetadata] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);
  useOutsideClose(menuOpen, menuRef, () => setMenuOpen(false));

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape" && !editingMetadata) onClose(); };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [onClose, editingMetadata]);

  const hasCampaign = Boolean(campaign.id);

  return (
    <div className="nomi-cc-backdrop" style={PREVIEW_BACKDROP_STYLE} role="presentation">
      <div className="nomi-campaign-preview-modal" style={PREVIEW_MODAL_STYLE} role="dialog" aria-modal="true" aria-label={`Preview: ${campaign.name}`}>
        <div className="nomi-campaign-preview-head" style={PREVIEW_HEAD_STYLE}>
          <div className="nomi-campaign-preview-heading" style={PREVIEW_HEADING_STYLE}>
            <h2 style={PREVIEW_H2_STYLE}>{campaign.name}</h2>
            <p style={PREVIEW_SUBJECT_STYLE}><b>Subject:</b> {subject || "No subject line yet — use Edit to add one."}</p>
            <p style={PREVIEW_SUBJECT_STYLE}><b>Preview text:</b> {previewText || "No preview text yet — use Edit to add one."}</p>
          </div>
          <div className="nomi-campaign-preview-actions" style={PREVIEW_ACTIONS_STYLE} ref={menuRef}>
            {hasCampaign ? (
              <>
                <button
                  type="button"
                  style={PREVIEW_EDIT_TRIGGER_STYLE}
                  aria-haspopup="menu"
                  aria-expanded={menuOpen}
                  onClick={() => setMenuOpen((open) => !open)}
                >
                  <svg width="13" height="13" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20l1-4L16 5l3 3L8 19l-4 1Z" fill="none" stroke="currentColor" strokeWidth="2" strokeLinejoin="round" strokeLinecap="round" /></svg>
                  Edit
                </button>
                {menuOpen ? (
                  <div style={PREVIEW_EDIT_MENU_STYLE} role="menu">
                    <button
                      type="button"
                      role="menuitem"
                      style={PREVIEW_EDIT_MENU_ITEM_STYLE}
                      onMouseDown={(e) => e.preventDefault()}
                      onClick={() => { setMenuOpen(false); setEditingMetadata(true); }}
                    >
                      Edit Subject & Preview Text
                    </button>
                    {campaign.html ? (
                      <Link
                        to={`/app/campaigns/edit?id=${campaign.id}`}
                        role="menuitem"
                        style={PREVIEW_EDIT_MENU_ITEM_STYLE}
                        onClick={() => setMenuOpen(false)}
                      >
                        Edit email template
                      </Link>
                    ) : null}
                  </div>
                ) : null}
              </>
            ) : null}
            <button type="button" style={PREVIEW_CLOSE_STYLE} aria-label="Close" onClick={onClose}>
              <svg width="15" height="15" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5l14 14M19 5L5 19" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" /></svg>
            </button>
          </div>
        </div>
        {campaign.html ? (
          <div className="nomi-campaign-preview-canvas" style={PREVIEW_CANVAS_STYLE}>
            <iframe title={`${campaign.name} preview`} srcDoc={campaign.html} style={PREVIEW_FRAME_STYLE} />
          </div>
        ) : (
          <p style={PREVIEW_EMPTY_STYLE}>No preview available for this campaign yet.</p>
        )}
      </div>
      {editingMetadata ? (
        <CampaignSubjectPreviewDialog
          campaignId={campaign.id}
          campaignName={campaign.name}
          subject={subject}
          previewText={previewText}
          onClose={() => setEditingMetadata(false)}
          onSaved={(result) => {
            setSubject(result.subject);
            setPreviewText(result.previewText);
          }}
        />
      ) : null}
    </div>
  );
}

const DIALOG_BACKDROP_STYLE: React.CSSProperties = {
  position: "fixed", inset: 0, zIndex: 560, display: "flex", alignItems: "center",
  justifyContent: "center", padding: 20, background: "rgba(32, 30, 29, .55)", boxSizing: "border-box",
};
const DIALOG_STYLE: React.CSSProperties = {
  width: "min(440px, 100%)", maxHeight: "88vh", overflowY: "auto", borderRadius: 12,
  background: "#ffffff", boxShadow: "0 30px 80px rgba(32, 30, 29, .3)", boxSizing: "border-box",
  display: "flex", flexDirection: "column",
};
const DIALOG_HEAD_STYLE: React.CSSProperties = {
  display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 14,
  padding: "20px 22px 14px", borderBottom: "1px solid #eae7e7", flexShrink: 0,
};
const DIALOG_TITLE_STYLE: React.CSSProperties = { margin: "2px 0 0", font: '600 17px/1.3 Lora, Georgia, serif', color: "#201e1d" };
const DIALOG_KICKER_STYLE: React.CSSProperties = { display: "block", font: '600 11px/1 "IBM Plex Sans", sans-serif', letterSpacing: ".04em", textTransform: "uppercase", color: "#0088b0" };
const DIALOG_CLOSE_STYLE: React.CSSProperties = { width: 28, height: 28, display: "grid", placeItems: "center", border: 0, borderRadius: 6, background: "transparent", color: "#605d5d", cursor: "pointer", flexShrink: 0 };
const DIALOG_BODY_STYLE: React.CSSProperties = { padding: "18px 22px", display: "flex", flexDirection: "column", gap: 16 };
const DIALOG_LABEL_ROW_STYLE: React.CSSProperties = { display: "flex", alignItems: "baseline", justifyContent: "space-between", marginBottom: 6 };
const DIALOG_LABEL_STYLE: React.CSSProperties = { font: '600 12.5px/1 "IBM Plex Sans", sans-serif', color: "#201e1d" };
const DIALOG_COUNT_STYLE: React.CSSProperties = { font: '500 11px/1 "IBM Plex Sans", sans-serif', color: "#716d6d" };
const DIALOG_COUNT_OVER_STYLE: React.CSSProperties = { ...DIALOG_COUNT_STYLE, color: "#d6006c" };
const DIALOG_INPUT_STYLE: React.CSSProperties = {
  width: "100%", height: 42, padding: "0 12px", boxSizing: "border-box", borderRadius: 8,
  border: "1.5px solid #d7d3d3", background: "#ffffff", color: "#201e1d",
  font: '13.5px/1 "IBM Plex Sans", sans-serif', outline: "none",
};
const DIALOG_TEXTAREA_STYLE: React.CSSProperties = {
  ...DIALOG_INPUT_STYLE, height: "auto", minHeight: 76, padding: "10px 12px", lineHeight: 1.4, resize: "vertical",
};
const DIALOG_ERROR_STYLE: React.CSSProperties = { margin: 0, padding: "9px 12px", borderRadius: 6, background: "color-mix(in srgb, #d6006c 10%, transparent)", color: "#d6006c", font: '600 12px/1.4 "IBM Plex Sans", sans-serif' };
const DIALOG_FOOT_STYLE: React.CSSProperties = { display: "flex", justifyContent: "flex-end", gap: 10, padding: "14px 22px 20px" };
const DIALOG_CANCEL_STYLE: React.CSSProperties = { height: 40, padding: "0 16px", borderRadius: 999, border: "1px solid #d7d3d3", background: "#ffffff", color: "#201e1d", font: '600 13px/1 "IBM Plex Sans", sans-serif', cursor: "pointer" };
const DIALOG_SAVE_STYLE: React.CSSProperties = { height: 40, padding: "0 18px", borderRadius: 999, border: 0, background: "#201e1d", color: "#f3f2f2", font: '600 13px/1 "IBM Plex Sans", sans-serif', cursor: "pointer" };
const DIALOG_SAVE_DISABLED_STYLE: React.CSSProperties = { ...DIALOG_SAVE_STYLE, background: "#d7d3d3", color: "#918d8d", cursor: "not-allowed" };

// The campaign-scoped counterpart of app._index.tsx's SubjectPreviewDialog
// (lifecycle recipes) — same fields, same validation shape, but posts to
// app.campaigns.metadata.tsx and updates a Campaign row instead of a
// BrandStudioProfile's approved recipe family.
function CampaignSubjectPreviewDialog({
  campaignId,
  campaignName,
  subject: initialSubject,
  previewText: initialPreviewText,
  onClose,
  onSaved,
}: {
  campaignId: string;
  campaignName: string;
  subject: string;
  previewText: string;
  onClose: () => void;
  onSaved: (result: { subject: string; previewText: string }) => void;
}) {
  const fetcher = useFetcher<CampaignMetadataActionResult>();
  const [subject, setSubject] = useState(initialSubject);
  const [previewText, setPreviewText] = useState(initialPreviewText);
  const subjectRef = useRef<HTMLInputElement>(null);
  const isSaving = fetcher.state !== "idle";
  const hasChanges = subject.trim() !== initialSubject.trim() || previewText.trim() !== initialPreviewText.trim();
  const isValid =
    subject.trim().length >= 3 && subject.trim().length <= 64 &&
    previewText.trim().length >= 3 && previewText.trim().length <= 140;

  useEffect(() => {
    subjectRef.current?.focus();
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape" && !isSaving) onClose(); };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [isSaving, onClose]);

  useEffect(() => {
    if (fetcher.state === "idle" && fetcher.data?.ok) {
      onSaved({ subject: fetcher.data.subject, previewText: fetcher.data.previewText });
      onClose();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [fetcher.state, fetcher.data]);

  return (
    <div style={DIALOG_BACKDROP_STYLE} role="presentation" onMouseDown={(e) => { if (e.target === e.currentTarget && !isSaving) onClose(); }}>
      <section style={DIALOG_STYLE} role="dialog" aria-modal="true" aria-label={`Edit subject and preview text for ${campaignName}`}>
        <div style={DIALOG_HEAD_STYLE}>
          <div>
            <span style={DIALOG_KICKER_STYLE}>Inbox details</span>
            <h3 style={DIALOG_TITLE_STYLE}>Edit subject &amp; preview</h3>
          </div>
          <button type="button" style={DIALOG_CLOSE_STYLE} onClick={onClose} disabled={isSaving} aria-label="Close">&times;</button>
        </div>
        <fetcher.Form method="post" action="/app/campaigns/metadata">
          <input type="hidden" name="campaignId" value={campaignId} />
          <div style={DIALOG_BODY_STYLE}>
            <label>
              <div style={DIALOG_LABEL_ROW_STYLE}>
                <span style={DIALOG_LABEL_STYLE}>Subject line</span>
                <span style={subject.length > 64 ? DIALOG_COUNT_OVER_STYLE : DIALOG_COUNT_STYLE}>{subject.length} / 64</span>
              </div>
              <input
                ref={subjectRef}
                type="text"
                name="subject"
                required
                minLength={3}
                maxLength={64}
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                style={DIALOG_INPUT_STYLE}
                autoComplete="off"
              />
            </label>
            <label>
              <div style={DIALOG_LABEL_ROW_STYLE}>
                <span style={DIALOG_LABEL_STYLE}>Preview text</span>
                <span style={previewText.length > 140 ? DIALOG_COUNT_OVER_STYLE : DIALOG_COUNT_STYLE}>{previewText.length} / 140</span>
              </div>
              <textarea
                name="previewText"
                required
                minLength={3}
                maxLength={140}
                rows={3}
                value={previewText}
                onChange={(e) => setPreviewText(e.target.value)}
                style={DIALOG_TEXTAREA_STYLE}
              />
            </label>
            {fetcher.data && !fetcher.data.ok ? <p style={DIALOG_ERROR_STYLE} role="alert">{fetcher.data.error}</p> : null}
          </div>
          <div style={DIALOG_FOOT_STYLE}>
            <button type="button" style={DIALOG_CANCEL_STYLE} onClick={onClose} disabled={isSaving}>Cancel</button>
            <button type="submit" style={!hasChanges || !isValid || isSaving ? DIALOG_SAVE_DISABLED_STYLE : DIALOG_SAVE_STYLE} disabled={isSaving || !hasChanges || !isValid}>
              {isSaving ? "Saving…" : "Save changes"}
            </button>
          </div>
        </fetcher.Form>
      </section>
    </div>
  );
}

// A verified domain becomes the From address (email-delivery/from-header.ts)
// and lifts the unverified campaign cap (SENDING_DOMAIN.md). Styled to match the merchant-approved reference
// banner (light-blue header strip, white body, outlined button). Every
// size is inline — see CAMPAIGNS.md on classes in the embedded iframe.
const DOMAIN_BANNER_DISMISS_KEY = "nomi:sending-domain-banner-dismissed";
const BANNER_FONT = 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif';

// Once verified, the banner shrinks to one quiet line so the merchant can
// still see which address sends and replay the three setup pages.
function SendingDomainVerifiedRow({ domain }: { domain: string }) {
  return (
    <section
      aria-label="Sending domain"
      style={{ margin: "16px 0", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap", padding: "6px 8px 6px 16px", background: "#fff", border: "1px solid #e3dfdb", borderRadius: 2, fontFamily: BANNER_FONT, color: "#201e1d" }}
    >
      <p style={{ margin: 0, display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", minWidth: 0, fontSize: 14, lineHeight: 1.45 }}>
        <span aria-hidden="true" style={{ width: 20, height: 20, flex: "none", display: "grid", placeItems: "center", borderRadius: "50%", background: "#0088b0", color: "#fff" }}>
          <svg width="11" height="11" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="M4.5 10.5 L8.5 14.5 L15.5 6" /></svg>
        </span>
        <span>Sending from <strong style={{ fontWeight: 600, wordBreak: "break-all" }}>hello@{domain}</strong></span>
        <span style={{ padding: "2px 8px", background: "#e6f4f8", color: "#006b8b", fontSize: 11, fontWeight: 700, letterSpacing: ".06em", textTransform: "uppercase" }}>Verified</span>
      </p>
      <Link
        to="/app/sending-domain?replay=1"
        style={{ minHeight: 44, display: "inline-flex", alignItems: "center", gap: 6, padding: "0 12px", color: "#0088b0", fontSize: 14, fontWeight: 600, textDecoration: "none", whiteSpace: "nowrap" }}
      >
        <svg width="15" height="15" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M3.5 10 A6.5 6.5 0 1 0 5.4 5.4" /><path d="M3.5 3.5 V7 H7" /></svg>
        Replay setup
      </Link>
    </section>
  );
}

function SendingDomainNotice({ sendingDomain }: { sendingDomain: { domain: string; status: string; verified: boolean } | null }) {
  const [dismissed, setDismissed] = useState(false);
  useEffect(() => {
    try { setDismissed(window.sessionStorage.getItem(DOMAIN_BANNER_DISMISS_KEY) === "1"); } catch { /* storage blocked */ }
  }, []);
  if (sendingDomain?.verified) return <SendingDomainVerifiedRow domain={sendingDomain.domain} />;
  if (dismissed) return null;

  const dismiss = () => {
    setDismissed(true);
    try { window.sessionStorage.setItem(DOMAIN_BANNER_DISMISS_KEY, "1"); } catch { /* storage blocked */ }
  };

  const copy = !sendingDomain
    ? { title: "Send from your own domain", body: `Verify your domain so your emails come from hello@yourstore.com instead of Nomi’s address. Without one you can create ${UNVERIFIED_CAMPAIGN_LIMIT} campaigns.`, cta: "Setup Domain" }
    : sendingDomain.status === "temporary_failure"
      ? { title: `A DNS record for ${sendingDomain.domain} went missing`, body: "Emails send from Nomi’s address until every record is back at your domain provider.", cta: "Fix Records" }
      : sendingDomain.status === "failed"
        ? { title: `Verification stopped for ${sendingDomain.domain}`, body: "The DNS records weren’t found after 72 hours. Add them, then restart verification.", cta: "Restart Setup" }
        : { title: `Finish verifying ${sendingDomain.domain}`, body: "Add the DNS records at your domain provider, then verify them in Nomi. Until then emails send from Nomi’s address.", cta: "Continue Setup" };

  return (
    <section
      aria-label="Sending domain status"
      style={{ margin: "16px 0", background: "#fff", borderRadius: 12, overflow: "hidden", boxShadow: "0 1px 0 rgba(26,26,26,.07), 0 1px 3px rgba(26,26,26,.18)", fontFamily: BANNER_FONT, color: "#303030" }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: 8, minHeight: 44, padding: "0 4px 0 16px", background: "#a4d0f8" }}>
        <svg width="18" height="18" viewBox="0 0 20 20" fill="none" stroke="#1a1a1a" strokeWidth="1.6" strokeLinecap="round" aria-hidden="true" style={{ flex: "none" }}>
          <circle cx="10" cy="10" r="7.25" /><path d="M10 9.2 V13.6" /><path d="M10 6.4 V6.5" strokeWidth="2" />
        </svg>
        <strong style={{ flex: 1, minWidth: 0, fontSize: 14, fontWeight: 650, lineHeight: 1.4, color: "#1a1a1a", padding: "10px 0" }}>{copy.title}</strong>
        <button
          type="button"
          onClick={dismiss}
          aria-label="Dismiss"
          style={{ width: 44, height: 44, flex: "none", display: "grid", placeItems: "center", padding: 0, margin: 0, border: 0, borderRadius: 8, background: "transparent", color: "#1a1a1a", cursor: "pointer" }}
        >
          <svg width="16" height="16" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" aria-hidden="true"><path d="M5 5 L15 15 M15 5 L5 15" /></svg>
        </button>
      </div>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16, flexWrap: "wrap", padding: "8px 16px" }}>
        <p style={{ margin: 0, flex: "1 1 280px", minWidth: 0, fontSize: 14, lineHeight: 1.45, color: "#303030" }}>{copy.body}</p>
        <Link
          to="/app/sending-domain"
          style={{ minHeight: 44, display: "inline-flex", alignItems: "center", flex: "none", textDecoration: "none" }}
        >
          <span style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", minHeight: 32, padding: "0 14px", background: "#fff", color: "#303030", border: 0, borderRadius: 8, boxShadow: "inset 0 -1px 0 #b5b5b5, 0 0 0 1px #d4d4d4", fontSize: 13, fontWeight: 650, whiteSpace: "nowrap", fontFamily: BANNER_FONT }}>{copy.cta}</span>
        </Link>
      </div>
    </section>
  );
}

export default function CampaignsPage() {
  // The route's loader also serves the picker's catalog-search JSON (the
  // `kind=products|collections` branches), so `typeof loader`'s inferred
  // return type is a union. Page navigation only ever hits the list branch
  // below, so this narrows to the shape this component actually renders.
  const { search, page, total, pageCount, campaigns, sendingDomain, campaignLimit } = useLoaderData() as {
    search: string;
    page: number;
    total: number;
    pageCount: number;
    sendingDomain: { domain: string; status: string; verified: boolean } | null;
    campaignLimit: { max: number; used: number; reached: boolean };
    campaigns: Array<{
      id: string;
      name: string;
      date: string;
      emails: number;
      status: string;
      subject: string;
      previewText: string;
      html: string;
    }>;
  };
  const pageHref = (target: number) => {
    const params = new URLSearchParams();
    if (search) params.set("q", search);
    params.set("page", String(target));
    return `?${params.toString()}`;
  };

  const generateFetcher = useFetcher<typeof action>();

  const [stage, setStage] = useState<ModalStage>("closed");
  const [prompt, setPrompt] = useState("");
  const [feature, setFeature] = useState<Feature>("product");
  const [selectedProduct, setSelectedProduct] = useState<CampaignCatalogProduct | null>(null);
  const [selectedCollection, setSelectedCollection] = useState<CampaignCatalogCollection | null>(null);
  const [selectedProducts, setSelectedProducts] = useState<CampaignCatalogProduct[]>([]);
  const [discountMethod, setDiscountMethod] = useState<DiscountMethod>("code");
  const [discountCode, setDiscountCode] = useState(() => randomDiscountCode());
  const [discountType, setDiscountType] = useState<DiscountType>("percentage");
  const [discountValue, setDiscountValue] = useState("25");
  const [startDate, setStartDate] = useState(() => isoDateOffset(0));
  const [startTime, setStartTime] = useState("09:00");
  const [endDate, setEndDate] = useState(() => isoDateOffset(3));
  const [endTime, setEndTime] = useState("23:59");
  const [generatingStep, setGeneratingStep] = useState(0);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const [reveal, setReveal] = useState<Reveal | null>(null);
  const [revealKey, setRevealKey] = useState(0);
  const [previewCampaign, setPreviewCampaign] = useState<{ id: string; name: string; subject: string; previewText: string; html: string } | null>(null);
  const timersRef = useRef<number[]>([]);

  const clearTimers = () => {
    timersRef.current.forEach((id) => window.clearTimeout(id));
    timersRef.current = [];
  };
  useEffect(() => clearTimers, []);

  const openCreate = () => {
    if (campaignLimit.reached) return;
    clearTimers(); setGenerateError(null); setStage("configure");
  };
  const closeModal = () => { clearTimers(); setStage("closed"); };

  // The dashboard's "Create your first campaign" links here with ?create=1.
  // Open the modal once, then drop the param so a reload doesn't reopen it.
  const [searchParams, setSearchParams] = useSearchParams();
  const createRequested = searchParams.get("create") === "1";
  useEffect(() => {
    if (!createRequested) return;
    openCreate();
    setSearchParams((params) => { params.delete("create"); return params; }, { replace: true });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [createRequested]);

  const discountSuffix = discountType === "percentage" ? "%" : "USD";

  const beginGenerating = () => {
    const trimmedPrompt = prompt.trim();
    if (!trimmedPrompt) { setGenerateError("Write what you want your campaign to be about."); return; }
    if (feature === "product" && !selectedProduct) { setGenerateError("Pick a product to feature."); return; }
    if (feature === "collection" && !selectedCollection) { setGenerateError("Pick a collection to feature."); return; }
    if (feature === "all_products" && selectedProducts.length === 0) { setGenerateError("Pick at least one product to feature."); return; }

    setGenerateError(null);
    clearTimers();
    setStage("generating");
    setGeneratingStep(0);

    const hasDates = discountMethod === "code" && startDate && endDate;
    const payload: GenerateCampaignRequest = {
      prompt: trimmedPrompt,
      feature,
      productIds:
        feature === "product" && selectedProduct ? [selectedProduct.id]
        : feature === "all_products" ? selectedProducts.map((product) => product.id)
        : [],
      collectionId: feature === "collection" ? selectedCollection?.id ?? null : null,
      discountMethod,
      discountCode: discountMethod === "code" ? discountCode : null,
      discountType,
      discountValue: discountMethod === "code" ? discountValue : null,
      startAt: hasDates ? `${startDate}T${startTime}` : null,
      endAt: hasDates ? `${endDate}T${endTime}` : null,
    };
    generateFetcher.submit({ payload: JSON.stringify(payload) }, { method: "post" });

    // Cycle through the phase labels while the real request is in flight,
    // capped one step short of the end so the animation never "finishes"
    // before the actual response arrives.
    const maxLiveStep = Math.max(0, AI_ROWS.length - 2);
    let step = 0;
    const interval = window.setInterval(() => {
      step = Math.min(step + 1, maxLiveStep);
      setGeneratingStep(step);
    }, AI_LIVE_STEP_MS);
    timersRef.current.push(interval as unknown as number);
  };

  // Finalizes the AI generate flow once the real server response lands.
  useEffect(() => {
    if (generateFetcher.state !== "idle" || !generateFetcher.data) return;
    const data = generateFetcher.data;
    if ("error" in data && data.error) {
      clearTimers();
      setGenerateError(data.error);
      setStage("configure");
      setGeneratingStep(0);
      return;
    }
    if ("campaign" in data && data.campaign) {
      const { campaign } = data;
      clearTimers();
      setGeneratingStep(AI_ROWS.length - 1);
      const timeout = window.setTimeout(() => {
        setStage("closed");
        setReveal({ id: campaign.id, title: campaign.name, subject: campaign.subject, preview: campaign.previewText, discountLine: campaign.discountLine, html: campaign.html });
        setRevealKey((key) => key + 1);
      }, SETTLE_MS);
      timersRef.current.push(timeout);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [generateFetcher.state, generateFetcher.data]);

  const showRedesignedEmpty = total === 0 && !reveal;
  const showReveal = Boolean(reveal);

  return (
    <main className="nomi-flow-page nomi-campaigns-page">
      <div className="nomi-flow-shell">
        <header className="nomi-flow-header">
          <div className="nomi-flow-title"><Link to="/app" className="nomi-flow-reference-arrow" aria-label="Back to home">←</Link><h1>Campaigns</h1></div>
          <div className="nomi-flow-header-actions" style={{ display: "flex", alignItems: "center", gap: 14, flexWrap: "wrap" }}>
            {!sendingDomain?.verified ? (
              <span id="campaign-limit-note" style={{ fontSize: 13, color: campaignLimit.reached ? "#a3004f" : "#605d5d" }}>
                {Math.min(campaignLimit.used, campaignLimit.max)} of {campaignLimit.max} campaigns used until your domain is verified
              </span>
            ) : null}
            <button
              type="button"
              className="nomi-flow-primary nomi-campaigns-create"
              onClick={openCreate}
              disabled={campaignLimit.reached}
              aria-describedby={!sendingDomain?.verified ? "campaign-limit-note" : undefined}
              title={campaignLimit.reached ? CAMPAIGN_LIMIT_MESSAGE : undefined}
              style={campaignLimit.reached ? { opacity: 0.45, cursor: "not-allowed" } : undefined}
            >
              <svg width="13" height="13" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" aria-hidden="true"><path d="M10 4 V16 M4 10 H16" /></svg>
              Create Campaign
            </button>
          </div>
        </header>

        <SendingDomainNotice sendingDomain={sendingDomain} />

        {showRedesignedEmpty ? (
          <div className="nomi-cc-empty">
            <div className="nomi-cc-empty-icon">
              <svg width="104" height="104" viewBox="0 0 120 120" aria-hidden="true">
                <circle cx="60" cy="60" r="50" fill="none" stroke="#e2ded8" strokeWidth="1.5" strokeDasharray="4 6" />
                <g transform="translate(35,25)">
                  <path d="M0 6a6 6 0 0 1 6-6h28l14 14v51a6 6 0 0 1-6 6H6a6 6 0 0 1-6-6Z" fill="#fff" stroke="#201e1d" strokeWidth="2" />
                  <path d="M34 0v14h14" fill="none" stroke="#201e1d" strokeWidth="2" strokeLinejoin="round" />
                  <rect x="9" y="13" width="11" height="11" rx="2" fill="#0088b0" />
                  <line x1="9" y1="32" x2="39" y2="32" stroke="#e2ded8" strokeWidth="3" strokeLinecap="round" />
                  <line x1="9" y1="41" x2="39" y2="41" stroke="#e2ded8" strokeWidth="3" strokeLinecap="round" />
                  <line x1="9" y1="50" x2="30" y2="50" stroke="#e2ded8" strokeWidth="3" strokeLinecap="round" />
                </g>
              </svg>
            </div>
            <div>
              <h2>No campaigns yet</h2>
              <p>Your campaigns will show up here once you create one.</p>
            </div>
            <button type="button" className="nomi-cc-empty-cta" onClick={openCreate} disabled={campaignLimit.reached}>Create Campaign</button>
          </div>
        ) : showReveal && reveal ? (
          <div className="nomi-cc-reveal" key={revealKey}>
            <p className="nomi-cc-reveal-count">1 campaign created</p>
            <div
              className="nomi-cc-reveal-card"
              role="button"
              tabIndex={0}
              aria-label={`Preview ${reveal.title}`}
              onClick={() => setPreviewCampaign({ id: reveal.id, name: reveal.title, subject: reveal.subject, previewText: reveal.preview, html: reveal.html })}
              onKeyDown={(event) => {
                if (event.key !== "Enter" && event.key !== " ") return;
                event.preventDefault();
                setPreviewCampaign({ id: reveal.id, name: reveal.title, subject: reveal.subject, previewText: reveal.preview, html: reveal.html });
              }}
            >
              <div className="nomi-cc-reveal-banner">
                <span className="nomi-cc-reveal-blob is-a" style={{ background: "#0088b0" }} />
                <span className="nomi-cc-reveal-blob is-b" style={{ background: "#d6006c" }} />
                <span className="nomi-cc-reveal-badge">{reveal.html ? "Click to preview" : "AI banner"}</span>
              </div>
              <div className="nomi-cc-reveal-body">
                <span className="nomi-cc-reveal-status">Draft</span>
                <h3 className="nomi-cc-reveal-title">{reveal.title}</h3>
                <p className="nomi-cc-reveal-subject"><b>Subject:</b> {reveal.subject}</p>
                <p className="nomi-cc-reveal-preview">{reveal.preview}</p>
                <div className="nomi-cc-reveal-foot">
                  <span>Created just now</span>
                  <span>{reveal.discountLine}</span>
                </div>
              </div>
            </div>
            <button type="button" className="nomi-cc-empty-cta" style={{ marginTop: 16 }} onClick={() => setReveal(null)}>View all campaigns</button>
          </div>
        ) : (
          <>

            <section className="nomi-campaigns-card" aria-label="Campaign list">
              <div className="nomi-campaigns-card-head">
                <span>{total} campaign{total === 1 ? "" : "s"}</span>
                <Form method="get" className="nomi-campaigns-search" role="search"><label htmlFor="campaign-search" className="nomi-visually-hidden">Search campaigns</label><input id="campaign-search" name="q" type="search" defaultValue={search} placeholder="Search campaigns" /><button type="submit" className="nomi-campaigns-icon-btn" aria-label="Search campaigns"><svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><circle cx="8.5" cy="8.5" r="5.5" /><path d="M13 13 L17 17" strokeLinecap="round" /></svg></button></Form>
              </div>

              <div className="nomi-table-responsive-wrap">
                <table className="nomi-campaigns-table"><colgroup><col style={{ width: "28%" }} /><col style={{ width: "14%" }} /><col style={{ width: "12%" }} /><col style={{ width: "12%" }} /><col style={{ width: "12%" }} /><col style={{ width: "12%" }} /><col style={{ width: "10%" }} /></colgroup><thead><tr><th>Campaign name</th><th>Updated</th><th>Emails</th><th>Open rate</th><th>Click rate</th><th>Revenue</th><th>Status</th></tr></thead>
                  <tbody>{campaigns.length ? campaigns.map((campaign) => <tr key={campaign.id}><td><button type="button" className="nomi-campaigns-name" onClick={() => setPreviewCampaign({ id: campaign.id, name: campaign.name, subject: campaign.subject, previewText: campaign.previewText, html: campaign.html })}>{campaign.name}</button></td><td className="nomi-campaigns-muted">{campaign.date}</td><td>{campaign.emails}</td><td>—</td><td>—</td><td>—</td><td><span className="nomi-campaigns-status">{campaign.status}</span></td></tr>) : <tr><td colSpan={7} className="nomi-campaigns-empty">{search ? `No campaigns match “${search}”.` : <><strong>No campaigns yet.</strong><span>Create a reviewed draft to see it here.</span></>}</td></tr>}</tbody>
                </table>
              </div>

              <div className="nomi-campaigns-pagination"><span>Page {page} of {pageCount}</span>{page > 1 ? <Link to={pageHref(page - 1)} className="nomi-campaigns-page-btn" aria-label="Previous page">‹</Link> : <button type="button" className="nomi-campaigns-page-btn" aria-label="Previous page" disabled>‹</button>}{page < pageCount ? <Link to={pageHref(page + 1)} className="nomi-campaigns-page-btn" aria-label="Next page">›</Link> : <button type="button" className="nomi-campaigns-page-btn" aria-label="Next page" disabled>›</button>}</div>
            </section>
          </>
        )}
      </div>

      {stage !== "closed" ? (
        <CreateCampaignModal
          stage={stage}
          onClose={closeModal}
          onGenerate={beginGenerating}
          generatingStep={generatingStep}
          prompt={prompt}
          onPromptChange={setPrompt}
          feature={feature}
          onFeatureProduct={() => setFeature("product")}
          onFeatureCollection={() => setFeature("collection")}
          onFeatureAllProducts={() => setFeature("all_products")}
          selectedProduct={selectedProduct}
          onSelectedProductChange={setSelectedProduct}
          selectedCollection={selectedCollection}
          onSelectedCollectionChange={setSelectedCollection}
          selectedProducts={selectedProducts}
          onSelectedProductsChange={setSelectedProducts}
          discountMethod={discountMethod}
          onDiscountCode={() => setDiscountMethod("code")}
          onDiscountNone={() => setDiscountMethod("none")}
          discountCode={discountCode}
          onDiscountCodeChange={setDiscountCode}
          onGenerateRandomCode={() => setDiscountCode(randomDiscountCode())}
          discountType={discountType}
          onDiscountTypeChange={setDiscountType}
          discountValue={discountValue}
          onDiscountValueChange={setDiscountValue}
          discountSuffix={discountSuffix}
          startDate={startDate}
          onStartDateChange={setStartDate}
          startTime={startTime}
          onStartTimeChange={setStartTime}
          endDate={endDate}
          onEndDateChange={setEndDate}
          endTime={endTime}
          onEndTimeChange={setEndTime}
          generateError={generateError}
        />
      ) : null}

      {previewCampaign ? (
        <CampaignPreviewModal campaign={previewCampaign} onClose={() => setPreviewCampaign(null)} />
      ) : null}
    </main>
  );
}

export const headers: HeadersFunction = (headersArgs) => boundary.headers(headersArgs);
